nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.1 --transmit_dim 50 >>SNR20dB50dim500temp >&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.1 --transmit_dim 72 >>SNR20dB72dim500temp >&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.1 --transmit_dim 80 >>SNR20dB80dim500temp >&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.1 --transmit_dim 96 >>SNR20dB96dim500temp >&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.1 --transmit_dim 100 >>SNR20dB100dim500temp >&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.3162 --transmit_dim 50 >>SNR10dB50dim500temp 2>&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.3162 --transmit_dim 72 >>SNR10dB72dim500temp 2>&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.3162 --transmit_dim 80 >>SNR10dB80dim500temp 2>&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.3162 --transmit_dim 96 >>SNR10dB96dim500temp 2>&1 &
wait
nohup python main_semantic_temp.py --offline --enc_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus 0, --generation_epoch 0 --lower_bound 0.95 --data_dir ./data --margin_max_distance 32 --known_dataset cifar_known --unknown_dataset imagenet-resize --data_transforms cifar --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.01 --step_size 100 --margin_jump 1.0 --margins_epoch 10 --batch_classes 10 --sample_count 8 --batch_size 400 --opt sgd --num_workers 0 --noise 0.3162 --transmit_dim 100 >>SNR10dB100dim500temp 2>&1 &
wait