# Static Channel Conditions
# PSNR = 20 dB LSUN
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 50 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_50/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 72 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_72/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 80 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_80/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 96 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_96/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 100 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_100/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_lsun 2>&1 &
wait

# PSNR = 20 dB IMAGENET
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 50 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_50/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 72 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_72/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 80 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_80/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 96 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_96/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 100 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_100/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait

# PSNR = 10 dB LSUN
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 50 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_50/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 72 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_72/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 80 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_80/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 96 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_96/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 100 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_100/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_lsun 2>&1 &
wait

# PSNR = 10 dB IMAGENET
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 50 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_50/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 72 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_72/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 80 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_80/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 96 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_96/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 100 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.3162/transmitdim_100/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  >>result/1_test_VIB_fig1_imagenet 2>&1 &
wait

# Dynamic Channel Conditions
# transmit 64 LSUN
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.2511 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1995 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1584 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1258 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_lsun 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_lsun 2>&1 &
wait

# transmit 64 IMAGENET
nohup python test_semantic_VIB.py --noise 0.3162 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.2511 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1995 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1584 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1258 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_VIB.py --noise 0.1 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_VIB_temp --checkpoint_path finalcheck/resnet18_semantic_VIB/cifar_known/noise_0.1/transmitdim_64/version_2/last.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 >>result/1_test_VIB_fig2_imagenet 2>&1 &
wait

