echo "开始执行脚本"
time {

# Static Channel Conditions
# PSNR = 20 dB LSUN
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 50 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_50/version_2/checkpoint-epoch=488-f1_score=0.765.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 72 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_72/version_2/checkpoint-epoch=473-f1_score=0.773.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 80 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_80/version_2/checkpoint-epoch=414-f1_score=0.778.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 96 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_96/version_2/checkpoint-epoch=490-f1_score=0.777.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 100 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_100/version_2/checkpoint-epoch=497-f1_score=0.774.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait

# PSNR = 20 dB IMAGENET
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 50 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_50/version_2/checkpoint-epoch=488-f1_score=0.765.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 72 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_72/version_2/checkpoint-epoch=473-f1_score=0.773.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 80 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_80/version_2/checkpoint-epoch=414-f1_score=0.778.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 96 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_96/version_2/checkpoint-epoch=490-f1_score=0.777.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 100 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_100/version_2/checkpoint-epoch=497-f1_score=0.774.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait

# PSNR = 10 dB LSUN
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 50 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_50/version_2/checkpoint-epoch=457-f1_score=0.757.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_64/version_2/checkpoint-epoch=460-f1_score=0.758.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 72 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_72/version_2/checkpoint-epoch=446-f1_score=0.761.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 80 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_80/version_2/checkpoint-epoch=450-f1_score=0.768.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 96 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_96/version_2/checkpoint-epoch=426-f1_score=0.770.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 100 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_100/version_2/checkpoint-epoch=438-f1_score=0.770.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_lsun 2>&1 &
wait

# PSNR = 10 dB IMAGENET
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 50 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_50/version_2/checkpoint-epoch=457-f1_score=0.757.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_64/version_2/checkpoint-epoch=460-f1_score=0.758.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 72 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_72/version_2/checkpoint-epoch=446-f1_score=0.761.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 80 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_80/version_2/checkpoint-epoch=450-f1_score=0.768.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 96 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_96/version_2/checkpoint-epoch=426-f1_score=0.770.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 100 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.3162/transmitdim_100/version_2/checkpoint-epoch=438-f1_score=0.770.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500  --ae_features >>result/test_ae_exit_proposed_fig1_imagenet 2>&1 &
wait

# Dynamic Channel Conditions
# transmit 64 LSUN
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.2511 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1995 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1584 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1258 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_lsun 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 64 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_lsun 2>&1 &
wait

# transmit 64 IMAGENET
nohup python test_semantic_temp.py --noise 0.3162 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.2511 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1995 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1584 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1258 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_imagenet 2>&1 &
wait
nohup python test_semantic_temp.py --noise 0.1 --transmit_dim 64 --unknown_dataset imagenet-resize --enc_type resnet18_semantic_temp --checkpoint_path finalcheck/resnet18_semantic_temp/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=475-f1_score=0.789.ckpt --offline --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --ae_features >>result/test_ae_exit_proposed_fig2_imagenet 2>&1 &
wait

# Early Exit LSUN

}
echo "脚本执行完毕"