nohup python test_semantic_temp_earlyexit.py --offline --noise 1.0 --unknown_dataset lsun-resize --transmit_dim 64 --enc_type resnet18_semantic_temp_early_exit --backbone_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --checkpoint_path checkpoints/resnet18_semantic_temp_early_exit/cifar_known/version_None/299.ckpt --ae_features --mode test_all_case >>earlyexit >&1 &
wait
nohup python test_semantic_temp_earlyexit.py --offline --noise 0.5623 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp_early_exit --backbone_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --checkpoint_path checkpoints/resnet18_semantic_temp_early_exit/cifar_known/version_None/299.ckpt --ae_features --mode test_all_case >>earlyexit >&1 &
wait
nohup python test_semantic_temp_earlyexit.py --offline --noise 0.3162 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp_early_exit --backbone_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --checkpoint_path checkpoints/resnet18_semantic_temp_early_exit/cifar_known/version_None/299.ckpt --ae_features --mode test_all_case >>earlyexit >&1 &
wait
nohup python test_semantic_temp_earlyexit.py --offline --noise 0.1778 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp_early_exit --backbone_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --checkpoint_path checkpoints/resnet18_semantic_temp_early_exit/cifar_known/version_None/299.ckpt --ae_features --mode test_all_case >>earlyexit >&1 &
wait
nohup python test_semantic_temp_earlyexit.py --offline  --noise 0.1 --unknown_dataset lsun-resize --enc_type resnet18_semantic_temp_early_exit --backbone_type resnet18_semantic_temp --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500 --checkpoint_path checkpoints/resnet18_semantic_temp_early_exit/cifar_known/version_None/299.ckpt --ae_features --mode test_all_case >>earlyexit >&1 &
wait
