nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_50/version_2/checkpoint-epoch=293-f1_score=0.716.ckpt --transmit_dim 50 --noise 0.1 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.1 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_72/version_2/checkpoint-epoch=298-f1_score=0.721.ckpt --transmit_dim 72 --noise 0.1 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_80/version_2/checkpoint-epoch=297-f1_score=0.734.ckpt --transmit_dim 80 --noise 0.1 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_96/version_2/checkpoint-epoch=290-f1_score=0.730.ckpt --transmit_dim 96 --noise 0.1 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_100/version_2/checkpoint-epoch=284-f1_score=0.727.ckpt --transmit_dim 100 --noise 0.1 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.3162 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.2518 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.1995 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.1584 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.1258 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.0794 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.0630 --unknown_dataset lsun-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait

nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_50/version_2/checkpoint-epoch=293-f1_score=0.716.ckpt --transmit_dim 50 --noise 0.1 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.1 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_72/version_2/checkpoint-epoch=298-f1_score=0.721.ckpt --transmit_dim 72 --noise 0.1 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_80/version_2/checkpoint-epoch=297-f1_score=0.734.ckpt --transmit_dim 80 --noise 0.1 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_96/version_2/checkpoint-epoch=290-f1_score=0.730.ckpt --transmit_dim 96 --noise 0.1 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_100/version_2/checkpoint-epoch=284-f1_score=0.727.ckpt --transmit_dim 100 --noise 0.1 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.3162 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.2518 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.1995 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.1584 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.1258 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.0794 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait
nohup python test_semantic_temp_change_position.py --checkpoint_path checkpoints/resnet18_semantic_temp_change_position/cifar_known/noise_0.1/transmitdim_64/version_2/checkpoint-epoch=350-f1_score=0.727.ckpt --transmit_dim 64 --noise 0.0630 --unknown_dataset imagenet-resize --ae_features --offline --enc_type resnet18_semantic_temp_change_position --latent_dim 32 --enc_out_dim 512 --max_epochs 500 --gpus "0," --generation_epoch 1 --lower_bound 0.98 --data_dir ./data --step_size 100 --margin_max_distance 32 --known_dataset cifar_known --data_transforms cifar_test --input_height 32 --class_num 10 --kl_coeff 0.1 --lr 0.1 --margin_jump 1.0 --margins_epoch 10 --batch_classes 1 --sample_count 4996 --batch_size 2500
wait